#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
GREEN='\033[0;32m'
NC='\033[0m'

echo "${GREEN}>>>>>>>>>> HUSKY pre-commit lint check <<<<<<<<<<${NC}" && yarn lint-staged && echo "${GREEN}>>>>>>>>>> HUSKY pre-commit lint check succeeded! <<<<<<<<<<${NC}"
